//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetIssues = new HashSet<AssetIssue>();
        }
    
        public long Id { get; set; }
        public long ItemMasterId { get; set; }
        public Nullable<System.Guid> GRNId { get; set; }
        public bool IsAssetized { get; set; }
        public string AssetTag { get; set; }
        public System.Guid AssetizedBy { get; set; }
        public System.DateTime AssetizedDate { get; set; }
        public string Comment { get; set; }
        public bool IsIssued { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual ICollection<AssetIssue> AssetIssues { get; set; }
    }
}
