//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.States = new HashSet<State>();
            this.VendorAddresses = new HashSet<VendorAddress>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<VendorAddress> VendorAddresses { get; set; }
    }
}
