//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryClassDepartmentMap
    {
        public System.Guid Id { get; set; }
        public long InventoryClassId { get; set; }
        public long DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual InventoryClass InventoryClass { get; set; }
    }
}
