//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.Assets = new HashSet<Asset>();
            this.IssuedItems = new HashSet<IssuedItem>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long ItemTypeId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<bool> Perishable { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<IssuedItem> IssuedItems { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
