//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public ItemType()
        {
            this.ItemMasters = new HashSet<ItemMaster>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int OrgId { get; set; }
        public long InventoryClassId { get; set; }
    
        public virtual InventoryClass InventoryClass { get; set; }
        public virtual ICollection<ItemMaster> ItemMasters { get; set; }
    }
}
