//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBankDetail
    {
        public long Id { get; set; }
        public long VendorId { get; set; }
        public string BeneficiaryName { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string MICR { get; set; }
        public string IFSC { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
