//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.VendorAddresses = new HashSet<VendorAddress>();
            this.VendorBankDetails = new HashSet<VendorBankDetail>();
            this.VendorContacts = new HashSet<VendorContact>();
            this.VendorTaxDetails = new HashSet<VendorTaxDetail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long LegalEntityId { get; set; }
        public string email { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int OrgId { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual ICollection<VendorAddress> VendorAddresses { get; set; }
        public virtual ICollection<VendorBankDetail> VendorBankDetails { get; set; }
        public virtual ICollection<VendorContact> VendorContacts { get; set; }
        public virtual ICollection<VendorTaxDetail> VendorTaxDetails { get; set; }
    }
}
