//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetIssue
    {
        public long Id { get; set; }
        public long AssetId { get; set; }
        public System.DateTime DateIssued { get; set; }
        public Nullable<System.Guid> IssuedTo { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> IssuedBy { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
