//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public System.Guid AttachmentId { get; set; }
        public byte[] FileContents { get; set; }
        public System.Guid EvaluationGoalId { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string EvaluationType { get; set; }
        public string FileSize { get; set; }
    }
}
