//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badge
    {
        public long Id { get; set; }
        public System.Guid ToBadge { get; set; }
        public Nullable<System.Guid> FromBadge { get; set; }
        public string BadgeType { get; set; }
        public bool Viewed { get; set; }
        public string Description { get; set; }
    }
}
