//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public long Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string CourseName { get; set; }
        public int YearOfPassing { get; set; }
        public string InstitutionName { get; set; }
        public string LevelDegree { get; set; }
        public string Marks { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
