//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        public long Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string Company { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string LastPositionHeld { get; set; }
        public string ReasonForLeaving { get; set; }
        public string JobDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
