//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationRating
    {
        public long EvalCycleId { get; set; }
        public System.Guid EmpId { get; set; }
        public Nullable<System.Guid> ManagerId { get; set; }
        public Nullable<decimal> SelfOverallRating { get; set; }
        public Nullable<decimal> ManagerOverllRating { get; set; }
        public Nullable<bool> HrApprovalStage1 { get; set; }
        public Nullable<bool> HrApprovalStage2 { get; set; }
        public string OverAllReviewComment { get; set; }
        public string OnGoingFeedBack { get; set; }
    }
}
