//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationCycle
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int OrgId { get; set; }
        public Nullable<System.DateTime> GoalStartDate { get; set; }
        public Nullable<System.DateTime> GoalEndDate { get; set; }
        public Nullable<System.DateTime> EvaluationStart { get; set; }
        public Nullable<System.DateTime> EvaluationEnd { get; set; }
    
        public virtual OrgLocation OrgLocation { get; set; }
    }
}
