//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public System.Guid gid { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Goal1 { get; set; }
        public bool Fixed { get; set; }
        public int OrgId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<long> Evalcycleid { get; set; }
        public Nullable<int> Weightage { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Rejected { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
