//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalStatu
    {
        public GoalStatu()
        {
            this.EmployeeEvaluations = new HashSet<EmployeeEvaluation>();
            this.ManagerEvaluations = new HashSet<ManagerEvaluation>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<EmployeeEvaluation> EmployeeEvaluations { get; set; }
        public virtual ICollection<ManagerEvaluation> ManagerEvaluations { get; set; }
    }
}
