//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryModuleAlert
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FromEmployee { get; set; }
        public string Message { get; set; }
        public string Url { get; set; }
        public System.Guid ToEmployee { get; set; }
        public string RelatedTo { get; set; }
        public string RelatedId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
