//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAttachment
    {
        public System.Guid Id { get; set; }
        public byte[] attachment { get; set; }
        public string filename { get; set; }
        public string mimetype { get; set; }
        public string entitytype { get; set; }
        public string entityid { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public long attachmentnumber { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
    }
}
