//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryClass
    {
        public InventoryClass()
        {
            this.InventoryClassDepartmentMaps = new HashSet<InventoryClassDepartmentMap>();
            this.ItemTypes = new HashSet<ItemType>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int OrgId { get; set; }
    
        public virtual ICollection<InventoryClassDepartmentMap> InventoryClassDepartmentMaps { get; set; }
        public virtual ICollection<ItemType> ItemTypes { get; set; }
    }
}
