//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        public InvoiceHeader()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.Payments = new HashSet<Payment>();
            this.SignOffCertificates = new HashSet<SignOffCertificate>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> POHeaderId { get; set; }
        public long VendorId { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public decimal Total { get; set; }
        public string Description { get; set; }
        public byte[] InvoiceScan { get; set; }
        public System.Guid EmployeeId { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public int OrgId { get; set; }
        public Nullable<System.Guid> QuoteId { get; set; }
        public Nullable<System.Guid> PurchaseRequestHeaderId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<short> PaymentStatus { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> IsFixedAsset { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> MiscTax { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual POHeader POHeader { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<SignOffCertificate> SignOffCertificates { get; set; }
    }
}
