//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPurchaseApprover
    {
        public System.Guid EmployeeId { get; set; }
        public long DepartmentId { get; set; }
        public Nullable<long> ValueFrom { get; set; }
        public Nullable<long> ValueTo { get; set; }
        public long Id { get; set; }
        public int OrgId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
