//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.Assets = new HashSet<Asset>();
            this.GRNLines = new HashSet<GRNLine>();
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.IssuedItems = new HashSet<IssuedItem>();
            this.POLines = new HashSet<POLine>();
            this.PurchaseRequestLines = new HashSet<PurchaseRequestLine>();
            this.QuoteLines = new HashSet<QuoteLine>();
            this.SignOffCertificates = new HashSet<SignOffCertificate>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long ItemTypeId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<bool> Perishable { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<long> Threshold { get; set; }
        public Nullable<int> UoM { get; set; }
        public Nullable<long> ItemLocation { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Make { get; set; }
        public string Color { get; set; }
        public Nullable<long> DepartmentId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<GRNLine> GRNLines { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<IssuedItem> IssuedItems { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual OrgLocation OrgLocation { get; set; }
        public virtual UOM UOM1 { get; set; }
        public virtual ICollection<POLine> POLines { get; set; }
        public virtual ICollection<PurchaseRequestLine> PurchaseRequestLines { get; set; }
        public virtual ICollection<QuoteLine> QuoteLines { get; set; }
        public virtual ICollection<SignOffCertificate> SignOffCertificates { get; set; }
    }
}
