//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerEvaluation
    {
        public System.Guid Id { get; set; }
        public System.Guid GoalId { get; set; }
        public System.Guid ManagerId { get; set; }
        public string Comment { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> GoalRating { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> EvalCycleId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        public virtual GoalStatu GoalStatu { get; set; }
    }
}
