//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageResource
    {
        public string MessageKey { get; set; }
        public string Message { get; set; }
        public string MessageType { get; set; }
        public int OrgId { get; set; }
        public Nullable<bool> Custom { get; set; }
    }
}
