//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Employees = new HashSet<Employee>();
            this.Goals = new HashSet<Goal>();
            this.RatingMasters = new HashSet<RatingMaster>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual ICollection<RatingMaster> RatingMasters { get; set; }
    }
}
