//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentDetails { get; set; }
        public string Note { get; set; }
        public bool IsPartialPayment { get; set; }
        public long PaymentMethodId { get; set; }
        public string TransactionRef { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
