//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class POHeader
    {
        public POHeader()
        {
            this.InvoiceHeaders = new HashSet<InvoiceHeader>();
            this.POLines = new HashSet<POLine>();
            this.SignOffCertificates = new HashSet<SignOffCertificate>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid QuoteId { get; set; }
        public long VendorId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> BillingAddressId { get; set; }
        public Nullable<long> ShippingAddressId { get; set; }
        public bool IncludeTermsAndConditions { get; set; }
        public string PaymentTerms { get; set; }
        public string WarrantyTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string TaxTerms { get; set; }
        public string OtherTerms { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> OrgId { get; set; }
        public int NumberOfApprovals { get; set; }
        public Nullable<System.Guid> Approver1 { get; set; }
        public Nullable<System.DateTime> Approval1Date { get; set; }
        public string Approver1Notes { get; set; }
        public Nullable<System.Guid> Approver2 { get; set; }
        public Nullable<System.DateTime> Approval2Date { get; set; }
        public string Approver2Notes { get; set; }
        public Nullable<int> ApprovalsRequired { get; set; }
        public Nullable<System.Guid> PurchaseRequestHeaderId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual OrgLocation OrgLocation { get; set; }
        public virtual OrgLocation OrgLocation1 { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<POLine> POLines { get; set; }
        public virtual ICollection<SignOffCertificate> SignOffCertificates { get; set; }
    }
}
