//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestHeader
    {
        public PurchaseRequestHeader()
        {
            this.PurchaseRequestLines = new HashSet<PurchaseRequestLine>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public long DepartmentId { get; set; }
        public string Justification { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Description { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> Approval1Date { get; set; }
        public string RefNo { get; set; }
        public bool Published { get; set; }
        public Nullable<System.Guid> Approver1 { get; set; }
        public string PurchaseRequestNumber { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<PurchaseRequestLine> PurchaseRequestLines { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
