//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteLine
    {
        public System.Guid Id { get; set; }
        public long ItemMasterId { get; set; }
        public int Qty { get; set; }
        public System.Guid QuoteId { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
