//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.POHeaders = new HashSet<POHeader>();
            this.QuoteLines = new HashSet<QuoteLine>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PurchaseRequestHeaderId { get; set; }
        public long VendorId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public byte[] ScannedQuote { get; set; }
        public string Description { get; set; }
        public decimal QuoteTotal { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalNotes { get; set; }
        public string QuoteNumber { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<POHeader> POHeaders { get; set; }
        public virtual PurchaseRequestHeader PurchaseRequestHeader { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<QuoteLine> QuoteLines { get; set; }
    }
}
