//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDeployment
    {
        public long ServiceDeploymentId { get; set; }
        public string SiteName { get; set; }
        public string RelativeServicePath { get; set; }
        public string RelativeApplicationPath { get; set; }
        public string ServiceName { get; set; }
        public string ServiceNamespace { get; set; }
    }
}
