//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignOffCertificate
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> GRNId { get; set; }
        public long ItemId { get; set; }
        public Nullable<System.Guid> VerifiedBy { get; set; }
        public Nullable<System.Guid> SignOffBy { get; set; }
        public string PutToUseNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public System.Guid PurchaseOrderId { get; set; }
        public long soc_idx { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual GRN GRN { get; set; }
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual POHeader POHeader { get; set; }
    }
}
