//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        public UOM()
        {
            this.ItemMasters = new HashSet<ItemMaster>();
        }
    
        public int Id { get; set; }
        public string UOM1 { get; set; }
    
        public virtual ICollection<ItemMaster> ItemMasters { get; set; }
    }
}
