//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFQueue
    {
        public string Username { get; set; }
        public System.Guid Wfid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public bool StartWf { get; set; }
        public string WFParam1 { get; set; }
        public string WFParam2 { get; set; }
        public string WFParam3 { get; set; }
    }
}
